CREATE TABLE "comms_messages" (
	"id" serial PRIMARY KEY NOT NULL,
	"job_id" text NOT NULL,
	"message_id" text NOT NULL,
	"thread_id" text,
	"direction" text,
	"stakeholder" text,
	"from_email" text,
	"to_email" text,
	"subject" text,
	"body_preview" text,
	"full_body" text,
	"sent_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "comms_messages_message_id_unique" UNIQUE("message_id")
);
--> statement-breakpoint
CREATE TABLE "job_comments" (
	"id" serial PRIMARY KEY NOT NULL,
	"job_id" text NOT NULL,
	"author_id" text,
	"author_name" text,
	"content" text NOT NULL,
	"type" text DEFAULT 'dispatch',
	"entity_id" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "jobs" (
	"id" serial PRIMARY KEY NOT NULL,
	"job_id" text NOT NULL,
	"timestamp" timestamp,
	"priority" text,
	"email_type" text,
	"category" text,
	"address" text,
	"unit" text,
	"description" text,
	"timing" text,
	"access_info" text,
	"rm_name" text,
	"rm_email" text,
	"tenant_name" text,
	"tenant_phone" text,
	"tenant_email" text,
	"pte" text,
	"estimate" text,
	"tech" text,
	"scheduled_date" text,
	"scheduled_time" text,
	"est_hours" real,
	"status" text,
	"notes" text,
	"gmail_msg_id" text,
	"calendar_event_id" text,
	"tenant_pref" text,
	"tenant_pets" text,
	"wc_code" text,
	"entity_id" text,
	"tracking_token" text,
	"tenant_scheduled" boolean DEFAULT false,
	"dispute_reason" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "jobs_job_id_unique" UNIQUE("job_id")
);
--> statement-breakpoint
CREATE TABLE "techs" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"badge" text,
	"rank" text,
	"phone" text,
	"pin_hash" text,
	"session_token" text,
	"token_expiry" timestamp,
	"role" text DEFAULT 'tech',
	"is_active" boolean DEFAULT true,
	"hourly_rate" real,
	"push_sub" text,
	"entity_id" text,
	"skill_carpentry" integer DEFAULT 0,
	"skill_plumbing" integer DEFAULT 0,
	"skill_electrical" integer DEFAULT 0,
	"skill_finish_carpentry" integer DEFAULT 0,
	"skill_structural" integer DEFAULT 0,
	"skill_landscaping" integer DEFAULT 0,
	"skill_janitorial" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "time_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"record_id" text NOT NULL,
	"job_id" text NOT NULL,
	"tech_id" text NOT NULL,
	"tech_name" text,
	"category" text,
	"address" text,
	"unit" text,
	"clock_in" timestamp,
	"clock_out" timestamp,
	"break_start" timestamp,
	"break_end" timestamp,
	"break_minutes" integer DEFAULT 0,
	"actual_hours" real,
	"est_hours" real,
	"status" text,
	"notes" text,
	"receipt_ids" text,
	"meal_warning" boolean DEFAULT false,
	"date" text,
	"lat_in" real,
	"lng_in" real,
	"lat_out" real,
	"lng_out" real,
	"entity_id" text,
	"attestation" text,
	"attestation_at" timestamp,
	"supervisor_status" text,
	"supervisor_id" text,
	"supervisor_name" text,
	"supervisor_at" timestamp,
	"dispute_reason" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "time_records_record_id_unique" UNIQUE("record_id")
);
