// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://aptmaintenanceinc.com
// Generated: 2026-06-08T01:18:14.385Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#404040' | '#000000' | '#ffffff' | '#1c3b7d' | '#4169e1' | '#223068' | '#999999' | '#ecd541' | '#2f4b86' | '#ebebeb' | '#c5c8be' | '#d1d4cc' | '#9ea7a7' | '#b4c1ba' | '#333333' | '#408bd1' | '#23282d' | '#00a0d2' | '#666666';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Raleway' | 'Times New Roman';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '500' | '600';

export type SpacingToken = '2px' | '18px' | '30px' | '36px' | '40px' | '43px' | '50px' | '54px' | '63px' | '67px' | '72px' | '80px' | '100px' | '110px' | '120px' | '128px' | '144px';

export type RadiusToken = '2px' | '10px' | '40px' | '100px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
