// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://dispatch.aptmaintenanceinc.com
// Generated: 2026-06-08T01:17:36.016Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary';
export type ColorHex  = '#1e293b' | '#ffffff' | '#0d0f14' | '#64748b';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = never;
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700' | '600';

export type SpacingToken = '2px' | '24px' | '32px';

export type RadiusToken = '12px' | '16px';

export type DurationToken = '150ms' | '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
