name: Cleanup Neon Preview Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-neon-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon preview branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: purple-dust-72858226
          branch: preview/${{ github.head_ref }}
          api_key: ${{ secrets.NEON_API_KEY }}
